src/components/common/Modal/Modal.tsx

<br>
<br>
<br>
- #13 
<br><br>

feat/modal: Modal 컴포넌트 열때 root 자식으로 추가되도록 createPortal 추가

---

package-lock.json
package.json

<br>
<br>
- 라이브러리 설치 후 package.json과 package-lock.json commit을 잊어버렸나봐요,,, 
pull 받아서 install하면 TagInput 컴포넌트 정상 작동하는 것을 확인 할 수 있습니다 :)
<br>
- #5 
<br><br>

bfm/page-main: Tagify 라이브러리 설치

---

src/components/mypage/ReservationListModal/ReservationListModal.module.css
src/components/mypage/ReservationListModal/ReservationListModal.tsx
src/components/mypage/ReservationManage/ReservationManage.module.css
src/components/mypage/ReservationManage/ReservationManage.tsx
src/components/mypage/index.tsx

<br>
<br>
<br>
- #15 
<br><br>

bfm/page-reservation-manage: 예매관리페이지 마크업 및 스타일

---

src/assets/menu.svg
src/assets/navbar-close.svg
src/components/layouts/Header/Header.module.css
src/components/layouts/Header/Header.tsx
src/components/layouts/NavBar/NavBar.module.css
src/components/mypage/NavigationBar/NavigationBar.module.css
src/components/mypage/Profile/Profile.module.css
src/global.css
src/pages/Mypage/Mypage.module.css

<br>
<br>
<br>
- #5 
- #15 
<br><br>

bfm/page-postmanage:  반응형 헤더, 마이페이지 사이드메뉴바구현 

---

src/components/common/index.tsx
src/components/main/StorySection/StorySection.tsx
src/components/mypage/PostManage/PostManage.tsx
src/components/mypage/ReservationManage/ReservationManage.tsx

<br>
-  index.tsx에 Filters export누락 수정
<br>
<br>
- #4 
- #5
- #15 
<br><br>

bfm/page-main: useModalStore로직 변경으로 따른 모달 열기/닫기 로직 수정

---

src/components/common/Button/Button.module.css
src/components/common/Button/Button.tsx
src/components/layouts/Header/Header.module.css
src/components/mypage/NavigationBar/NavigationBar.module.css
src/components/mypage/PostManage/PostManage.module.css
src/components/mypage/PostManage/PostManage.tsx
src/components/mypage/PostUpload/PostUpload.module.css
src/components/mypage/ReservationManage/ReservationManage.tsx
src/pages/Mypage/Mypage.module.css
src/pages/Mypage/Mypage.tsx

<br>
- 마이페이지 페이지 반응형에 맞게 스타일 수정
<br>
- 햄버거 navbar 생기는 기준 560px -> 768px (태블릿 너비 기준)으로 변경했습니당
- 햄버거 navbar 생길때 제목이 없어서 어떤 페이지인지 인지하기 어려운 것 같아서 heading 추가했습니다 (아래 사진 참고)
- Button 컴포넌트 스타일 제어가 힘들어서 style props 추가했어요
- 예매관리 페이지도 반응형 적용할 예정
<br>
-
<br><br>

bfm/responsive: 반응형 관련 스타일 수정

---

src/apis/getBannerImages.ts
src/apis/index.ts
src/components/common/Carousel/Carousel.tsx
src/components/common/Carousel/slick.css
src/components/main/Banner/Banner.module.css
src/components/main/Banner/Banner.tsx
src/components/main/StoryViewModal/StoryViewModal.module.css
src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
src/types/showType.ts

<br>
<br>
- 모달 반응형 완벽하진 않으니 pull 받아서 반응형 도와주세여 ㅠㅠ
<br>
- #2 
- #4 
<br><br>

feat/page-main: 메인페이지 배너 api 연결 및 스토리 모달 반응형 구현

---

src/Router.tsx
src/components/layouts/Header/Header.tsx
src/components/mypage/NavigationBar/NavigationBar.tsx
src/pages/Mypage/Mypage.tsx

refactor/mypage-router: 마이페이지 라우팅 방식 변경 (querystring -> pathname)

---

src/components/mypage/LikeManage/LikeManage.module.css
src/components/mypage/LikeManage/LikeManage.tsx
src/components/mypage/NavigationBar/NavigationBar.tsx
src/pages/Mypage/Mypage.tsx

<br>
<br>
- 스포츠는 일단 넣지 않았습니다.
- 기존에 사용하고 있는 컴포넌트를 가지고 올 때, 폰트 사이즈가 너무 커서 부분 조정 했습니다.
<br>
- #15 
<br><br>

bfm/page-mypage-like : 좋아요 관리 페이지 마크업 및 스타일 및 네비게이션 유저, 관리자 구분 리팩토링

---

src/apis/getUserLikeList.ts
src/apis/index.ts
src/components/mypage/LikeManage/LikeManage.module.css
src/components/mypage/LikeManage/LikeManage.tsx

<br>
<br>
- 이거 git 사진 크기 어떻게 줄여요...?
- bfm 먼저 merge 해주세여~~~~~~
<br>
- #15 #45 
<br><br>

feat/page-mypage-like : 마이페이지 좋아요 관리 API 통신 후 출력 및 반응형

---

src/components/main/Postcode/Postcode.tsx
src/components/mypage/PostUpload/PostUpload.tsx
src/utils/formattingDate.ts

<br>
- Postcode 컴포넌트에서 좌표 구할 때 async/await 처리
- 날짜 스트링 포맷 변경 (2023/00/00 -> 2023-00-00)
- 회차정보(date_time) 데이터 보낼때 convertArrayToObject 적용
<br>
<br>
- #45 
- #53 
<br><br>

feat/page-mypage-show-upload: 게시글 업로드 toast 적용, 유효성 검사 추가, 기타 버그 수정

---

src/components/mypage/LikeManage/LikeManage.tsx
src/components/mypage/NavigationBar/NavigationBar.tsx
src/components/mypage/ReviewManage/ReviewManage.module.css
src/components/mypage/ReviewManage/ReviewManage.tsx
src/components/mypage/ReviewMypageItem/ReviewMypageItem.module.css
src/components/mypage/ReviewMypageItem/ReviewMypageItem.tsx
src/utils/isInDay.ts
src/utils/isWithinOneDay.ts

<br>
<br>
- border 색이 너무 연한데 좀 찐하게 할까요???
<br>
- #15 
<br><br>

bfm/page-mypage-review : 리뷰 페이지 마크업 및 디자인

---

src/apis/deleteLike.ts
src/apis/deleteReview.ts

<br>
-  Delete 메소드 쓰는 api 스펙 변경(Delete와 Get은 body를 쓰지 않는게 좋다고 해서)으로 기존 함수가 정상적으로 작동을 안해서 고치게 되었습니다!
- body 대신 path parameter로 변경
<br>
<br>
- #1 
<br><br>

feat/page-detail-like: Delete api body 대신 path parameter로 변경

---

src/components/common/DeleteButton/DeleteButton.tsx
src/components/mypage/StoryItem/StoryItem.module.css
src/components/mypage/StoryItem/StoryItem.tsx
src/components/mypage/StoryManage/StoryManage.module.css
src/components/mypage/StoryManage/StoryManage.tsx

<br>
<br>
-
<br>
- #4 #15 
<br><br>

bfm/page-mypage-story : 마이페이지 story 마크업 및 디자인

---

src/components/mypage/Reservation/Reservation.module.css
src/components/mypage/Reservation/Reservation.tsx

<br>
TODO
- 예매 정보 클릭 시 모달 뜨게 하기
<br>
<br>
<br>
- #15 
<br><br>

bfm/page-mypage-reservation : 마이페이지 유저 예약 관리 디자인 및 마크업

---

src/apis/getUserReviewList.ts
src/apis/index.ts
src/components/mypage/ReviewManage/ReviewManage.tsx
src/components/mypage/ReviewMypageItem/ReviewMypageItem.tsx
src/types/reviewType.ts

<br>
<br>
- 이전 pr 먼저 머지 해주세요~
- 댓글 클릭하면 해당 댓글 위치로 이동해야 되는지...?? 를 넣어야 될까요 ㅋ
<br>
- #45 
<br><br>

feat/page-mypage-review : 마이페이지 review 조회 및 삭제 기능 추가 

---

src/apis/getUserInfo.tsx
src/pages/Signup/SignupPage.tsx

<br>
- 회원가입 ID 중복 확인 API 수정
<br>
-
<br>
- #9 
<br><br>

feat/page-signup : 회원가입 id 중복 검증 로직 수정

---

src/Router.tsx
src/apis/deleteShow.ts
src/apis/index.ts
src/apis/putShow.ts
src/components/common/InputField/InputField.tsx
src/components/common/RadioButtonGroup/RadioButtonGroup.tsx
src/components/mypage/PostManage/PostManage.tsx
src/components/mypage/PostUpdate/PostUpdate.module.css
src/components/mypage/PostUpdate/PostUpdate.tsx
src/components/mypage/PostUpload/PostUpload.tsx
src/components/mypage/ReservationForm/ReservationForm.tsx
src/types/showReservationInfoType.ts
src/types/showType.ts

<br>
- 게시글 수정
- 게시글 삭제
<br>
- 나중에 게시글 업로드 페이지랑 코드 합칠 수 있으면 합쳐볼게요 ㅎㅎ
<br>
- #45
<br><br>

feat/page-mypage-show-update: 게시글 수정, 삭제 기능 구현

---

src/PrivateRoute.tsx
src/apis/getSignUserInfo.ts
src/apis/getUserInfo.tsx
src/apis/index.ts
src/components/common/Button/Button.tsx
src/components/common/DatePicker/DatePicker.tsx
src/components/common/Editor/Editor.tsx
src/components/common/InputFieldGroup/InputFieldGroup.tsx
src/components/detail/GuestAccess/GuestAccess.tsx
src/components/detail/InfoSection/InfoSection.tsx
src/components/detail/ReservationForm/ReservationForm.tsx
src/components/main/Postcode/Postcode.tsx
src/components/mypage/NavigationBar/NavigationBar.tsx
src/components/mypage/PostManage/PostManage.tsx
src/components/mypage/PostUpdate/PostUpdate.tsx
src/components/mypage/Reservation/Reservation.tsx
src/components/mypage/ReservationForm/ReservationForm.tsx
src/components/mypage/ReviewManage/ReviewManage.tsx
src/components/mypage/StoryManage/StoryManage.tsx
src/hooks/useFilterSlide.tsx
src/hooks/useInputs.tsx
src/main.tsx
src/pages/Error/ErrorPage.tsx
src/pages/Mypage/Mypage.tsx
src/pages/Signup/SignupPage.tsx
src/types/showReservationInfoType.ts
src/utils/dateSelect.ts

<br>
- **npm run build시 발견된 에러 및 버그 수정**
- type 관련
: 불필요한 import 제거, 사용하지않는 변수 언더바(_)처리, 누락된 type 지정
- 버그
- 회원가입 페이지에 getUserInfo API를 잘 못 사용하고 있었어서 getSignUserInfo API 생성 및 적용했습니다
- 예매 모달창에 디코딩 적용안된게 있어서 수정했어요
<br>
-
<br>
- 
<br><br>

fix/types-etc: 타입관련 에러 및 버그 수정

---

src/pages/Login/LoginPage.tsx

<br>
- 로그인 시 메인페이지로 이동
-
<br>
-
<br>
- #3 
<br><br>

feat/page-login: 로그인 시 메인 페이지로 이동

---

src/apis/getAdminReservationDetail.ts
src/apis/getAdminReservationList.ts
src/apis/index.ts
src/components/common/Modal/Modal.module.css
src/components/layouts/Header/Header.tsx
src/components/mypage/NavigationBar/NavigationBar.tsx
src/components/mypage/PostManage/PostManage.module.css
src/components/mypage/PostManage/PostManage.tsx
src/components/mypage/ReservationListModal/ReservationListModal.module.css
src/components/mypage/ReservationListModal/ReservationListModal.tsx
src/components/mypage/ReservationManage/ReservationManage.module.css
src/components/mypage/ReservationManage/ReservationManage.tsx
src/global.css

<br>
- location.pathname 바뀔때 마이페이지 사이드 네비게이션 바 닫히지 않는 버그 해결
- 예매관리 리스트, 상세 리스트 가져오는 기능 구현
<br>
- 회색 스크롤바 공통 css global로 빼고 class 적용 
<br>
- #4 #15 
<br><br>

feat/page-reservation-manage: 관리자 마이페이지 예약관리 리스트 불러오기 기능 구현

---

src/components/layouts/Header/Header.tsx

fix: 불필요한 import 제거

---

src/App.tsx
src/components/detail/InfoSection/InfoSection.tsx
src/components/detail/ReviewSection/ReviewSection.tsx
src/components/detail/SubMenuBar/SubMenuBar.tsx
src/components/detail/SubMenuSection/SubMenuSection.tsx

feat/page-detail: 상세 페이지에서 후기 없을 때 보여줄 화면 추가 및 스크롤 탑 기능 추가

---

src/components/common/BasicCard/BasicCard.module.css
src/components/common/Carousel/Carousel.tsx
src/components/common/Modal/Modal.module.css
src/components/common/TicketCard/TicketCard.module.css
src/components/common/TicketCard/TicketCard.tsx
src/components/main/Banner/Banner.module.css
src/components/main/Banner/Banner.tsx
src/components/main/StoryCard/StoryCard.module.css
src/components/main/StorySection/StorySection.tsx
src/components/main/StoryUploadModal/StoryUploadModal.module.css
src/components/main/StoryUploadModal/StoryUploadModal.tsx
src/components/main/StoryViewModal/StoryViewModal.module.css
src/components/main/StoryViewModalCard/StoryViewModalCard.module.css
src/components/main/StoryViewModalCard/StoryViewModalCard.tsx

<br>
- 보더 얇게하고 래디우스 주고 그런 자잘한 스타일 수정했어요
<br/>
<br />
- 이미지 배너 3개로 변경했어요
<br>
-
<br>
- #2 
- #4 
<br><br>

style/page-main: 메인페이지 컴포넌트들 스타일 수정

---

src/apis/getAdminReservationDetail.ts
src/components/mypage/admin/ReservationListModal/ReservationListModal.module.css
src/components/mypage/admin/ReservationListModal/ReservationListModal.tsx
src/pages/Mypage/admin/PostManage/PostManagePage.tsx

<br>
- ReservationListModal 이름, 이메일, 핸드폰번호, 결제날짜로 마크업 변경
- 
<br>
- PostManagePage a11y-hidden 부분 없앴더니 스크롤 오류가 사라졌는데 왜그런건지 모르겠습니다 ㅠ
<br>
- #15 
<br><br>

feat/page-admin-reservation: ReservationListModal 이름, 이메일, 핸드폰번호, 결제날짜 추가

---

src/components/main/StoryUploadModal/StoryUploadModal.tsx
src/pages/Mypage/admin/PostUpdate/PostUpdatePage.tsx
src/pages/Mypage/admin/PostUpload/PostUploadPage.tsx

<br>
- 글 업로드, 수정, 삭제 / 스토리 업로드 성공시 toast.info 대신 toast.success로 변경
-
<br>
<br>
-
<br><br>

feat/page-main: toast alert 기능성공시 toast.info에서 toast.success로 변경

---

src/pages/Mypage/user/ReservationManage/ReservationManagePage.tsx

<br>
<br>
<br>
- #45 
<br><br>

feat/page-mypage-reservation : 예매 정보 모달 창 height 제거

---

src/PrivateRoute.tsx

<br>
- 관리자나 유저가 본인 마이페이지가 아닌 다른 접근 경로로 이동 시 메인 페이지로 강제 이동
-
<br>
-
<br>
-
<br><br>

hotFix: PrivateRoute 일반 유저, 관리자 접근 권한 수정

---

src/components/detail/InfoSection/InfoSection.module.css

<br>
- 텍스트 줄바꿈 css 스타일 수정
<br>
- 예매 모달창에서 텍스트가 벗어나는지는 로그인 버그 해결 후 다시 확인해보겠습니다
<br>
- #1 
- #104 
<br><br>

feat/page-detail: 상세 페이지 줄바꿈 스타일 수정

---

src/main.tsx

<br>
- axios의 withCredentials 설정이 없어 쿠키를 포함한 인증이 요구되는 요청에서 문제가 발생
- axios.defaults.withCredentials = true를 main.tsx에 추가하여 모든 API 요청에 자동으로 쿠키를 포함 시키도록 설정
<br>
<br>
- #101 
<br><br>

refactor/axios-config : axios 자격 증명 설정

---

src/hooks/index.tsx
src/hooks/useResizeZoom.tsx
src/pages/Login/LoginPage.module.css
src/pages/Login/LoginPage.tsx
src/pages/Mypage/Mypage.module.css
src/pages/Mypage/ProfilePage/ProfilePage.tsx
src/pages/Signup/SignupPage.module.css
src/pages/Signup/SignupPage.tsx

<br>
- 기존 반응형 페이지
| <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/dcb90856-6613-4840-a368-9e4af47559b1"  width="500" /> | <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/56d2b459-5bfd-4fe8-9e60-9dc9307e87cc" width="500" /> | <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/04bdcee1-9082-44a4-97e3-0abadb553509" width="500" /> |
| :--------: | :--------: | :--------: |
| 로그인 | 회원가입 | 마이페이지 |
- Resize zoom 적용
| <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/632bb644-5330-42e7-a0f7-2f24c26eb525" width="500" /> | <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/a86c61f2-ffef-424b-96a7-f30200292cfa" width="500" /> | <img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/7867 …

refactor/resize-zoom : 페이지 Resize zoom 적용

---

src/App.tsx
src/components/common/UserAccessModal/UserAccessModal.tsx
src/components/layouts/Header/Header.tsx
src/pages/Login/LoginPage.tsx

<br>
<br>
<br>
- #3 #4 
<br><br>

refactor/redirect-privateroute : 로그인 시 이전 위치로 이동 및 PrivateRoute 마이페이지로 이동할 때만 적용

---

src/hooks/useGetShowResInfoQuery.tsx

<br>
- 기존 코드는 main에서 export하던 queryClient를 import 받아서 사용했었는데 useQueryClient 훅 사용으로 로직 변경
<br>
- #123 PR에서 작업이 덜됐나봐요! 그래서 고쳤습니다! 해당 PR먼저 머지해주세요 :) 
<br>
- #119 
<br><br>

refactor/error-handling: useGetShowResInfoQuery 훅 useQueryClient 사용

---

src/pages/Error/NetworkErrorPage.tsx

bfm/network-error: 네트워크 에러 페이지 마크업 및 스타일
